/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chat: typeof import('./src/components/chat.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CloudinaryUploadButton: typeof import('./src/components/CloudinaryUploadButton.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GeneralTeams: typeof import('./src/components/GeneralTeams.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homeworks: typeof import('./src/components/homeworks.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ManualCldImage: typeof import('./src/components/ManualCldImage.vue')['default']
    ManualCldVideo: typeof import('./src/components/ManualCldVideo.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Notifications: typeof import('./src/components/notifications.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teams: typeof import('./src/components/teams.vue')['default']
    UseProfile: typeof import('./src/components/useProfile.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
