version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: poi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'db_poi_v1'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - poi_network

volumes:
  mysql_data:
    name: poi_mysql_data

networks:
  poi_network:
    name: poi_network 